import { WeekMeta, UserParams } from '@/types/plan';

export function buildCoachPrompt({
  userParams,
  weekMeta,
  index,
}: {
  userParams: UserParams;
  weekMeta: WeekMeta;
  index: number;
}): string {
  return `
You are an expert triathlon coach creating week ${index + 1} of a ${userParams.raceType} training plan for an athlete.

## Athlete Profile
- Race Type: ${userParams.raceType}
- Race Date: ${userParams.raceDate.toISOString().split('T')[0]}
- Experience Level: ${userParams.experience}
- Max Training Hours per Week: ${userParams.maxHours}
- Rest Day: ${userParams.restDay}

## Week Details
- Week Label: ${weekMeta.label}
- Phase: ${weekMeta.phase}
- Start Date: ${weekMeta.startDate}
- Deload Week: ${weekMeta.deload ? 'Yes' : 'No'}

## Performance Metrics (if provided)
${userParams.bikeFTP ? `- Bike FTP: ${userParams.bikeFTP} watts` : ''}
${userParams.runPace ? `- Run Pace: ${userParams.runPace} per mile` : ''}
${userParams.swimPace ? `- Swim Pace: ${userParams.swimPace} per 100m` : ''}

## Instructions
- Generate 5-6 workouts for this week, balancing swim, bike, and run.
- Include a full rest day.
- Use brick workouts on weekends if appropriate.
- Progress intensity and volume appropriately.
- Format your response as strict JSON, exactly like this example:

{
  "label": "${weekMeta.label}",
  "phase": "${weekMeta.phase}",
  "startDate": "${weekMeta.startDate}",
  "deload": ${weekMeta.deload},
  "days": {
    "YYYY-MM-DD": ["Workout 1", "Workout 2"],
    ...
  },
  "debug": "This is week ${index + 1} generated by the AI coach."
}

Return **only** valid JSON — no explanations or extra text.
  `.trim();
}
