// Optional test runtime: set PGLITE_TEST_MODULE to an installed PGlite module URL.
const { PGlite } = await import(process.env.PGLITE_TEST_MODULE || '@electric-sql/pglite');
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const db = new PGlite();
const user='00000000-0000-0000-0000-000000000001', other='00000000-0000-0000-0000-000000000002';
const plan='10000000-0000-0000-0000-000000000001', session='20000000-0000-0000-0000-000000000001', second='20000000-0000-0000-0000-000000000002';
await db.exec(`create schema auth; create role anon; create role authenticated; create role service_role;
create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
grant usage on schema public,auth to authenticated; grant execute on function auth.uid() to authenticated;
create table public.plans(id uuid primary key,user_id uuid not null unique,plan jsonb);
create table public.sessions(id uuid primary key,user_id uuid,plan_id uuid,date date not null,sport text,title text,session_title text,duration integer,details text,raw jsonb,status text default 'planned',strava_id uuid);
create table public.completed_sessions(id uuid primary key default gen_random_uuid(),created_at timestamptz default now(),user_id uuid,plan_id uuid default auth.uid(),date date,sport text,status text constraint status_check check(status in ('done','skipped') or status is null),session_title text,
constraint completed_sessions_unique unique(user_id,date,sport));
alter table public.plans enable row level security; alter table public.completed_sessions enable row level security;
create policy own_plans on public.plans for all to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy own_completed on public.completed_sessions for all to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);
grant select,insert,update,delete on public.plans,public.sessions,public.completed_sessions to authenticated;
insert into auth.users values('${user}'),('${other}');
insert into public.plans values('${plan}','${user}','{}');
insert into public.sessions(id,user_id,plan_id,date,sport,title) values('${session}','${user}','${plan}','2027-01-07','run','Long Run'),('${second}','${user}','${plan}','2027-01-07','run','Easy Run');
insert into public.completed_sessions(user_id,date,sport,session_title,status) values('${user}','2026-01-01','run','Historical Run','done');`);
for(const file of ['20260930001606_linked_session_completion.sql','20260930001847_training_pauses.sql','20261001032546_preserve_completion_history_and_moves.sql']) await db.exec(await readFile(new URL('../supabase/migrations/'+file,import.meta.url),'utf8'));
await db.exec(`set role authenticated; select set_config('request.jwt.claim.sub','${user}',false);`);
await db.query(`select public.set_session_completion($1,'done',false)`,[session]);
await db.query(`select public.set_session_completion($1,'done',false)`,[second]);
const completed = (await db.query('select * from public.completed_sessions where session_id=$1',[session])).rows[0];
assert.equal(completed.date.toISOString().slice(0,10),'2027-01-07'); assert.ok(completed.completed_at); assert.equal(completed.plan_id,plan);
await db.query(`select public.set_session_completion($1,'done',false)`,[session]);
assert.equal((await db.query('select count(*)::int as n from public.completed_sessions where session_id=$1',[session])).rows[0].n,1);
assert.equal((await db.query('select completed_at from public.completed_sessions where session_id=$1',[session])).rows[0].completed_at.toISOString(),completed.completed_at.toISOString());
await db.query(`select public.set_session_completion($1,'done',true)`,[session]);
assert.equal((await db.query('select status from public.completed_sessions where session_id=$1',[session])).rows[0].status,'planned');
assert.equal((await db.query("select count(*)::int as n from public.completed_sessions where session_title='Historical Run'")).rows[0].n,1);
const pause = (await db.query(`insert into public.training_pauses(user_id,plan_id,started_date,reason) values($1,$2,'2027-01-04','travel') returning id`,[user,plan])).rows[0].id;
await assert.rejects(()=>db.query(`insert into public.training_pauses(user_id,plan_id,started_date,reason) values($1,$2,'2027-01-04','sick')`,[user,plan]),/unique/);
await db.query(`select public.resume_training($1,'2027-01-08','normal','{}','{}','[]')`,[pause]);
assert.equal((await db.query('select status from public.training_pauses where id=$1',[pause])).rows[0].status,'resumed');
const easePause = (await db.query(`insert into public.training_pauses(user_id,plan_id,started_date,reason) values($1,$2,'2027-01-08','life') returning id`,[user,plan])).rows[0].id;
const update = [{ id: session, expected_date: '2027-01-07', expected_title: 'Long Run', title: 'Easy Return Run', duration: 45, details: 'Easy aerobic', raw: { durationMinutes: 45 } }];
await assert.rejects(()=>db.query(`select public.resume_training($1,'2027-01-09','ease','{"changed":true}','{}',$2::jsonb)`,[easePause,JSON.stringify(update)]),/Plan changed/);
assert.equal((await db.query('select status from public.training_pauses where id=$1',[easePause])).rows[0].status,'paused');
await db.query(`select public.resume_training($1,'2027-01-09','ease','{}','{"returnWeek":true}',$2::jsonb)`,[easePause,JSON.stringify(update)]);
assert.equal((await db.query('select title,duration from public.sessions where id=$1',[session])).rows[0].duration,45);
assert.equal((await db.query('select plan from public.plans where id=$1',[plan])).rows[0].plan.returnWeek,true);
const conflictPause = (await db.query(`insert into public.training_pauses(user_id,plan_id,started_date,reason) values($1,$2,'2027-01-09','travel') returning id`,[user,plan])).rows[0].id;
const completedUpdate = [{ ...update[0], id: second, expected_title: 'Easy Run' }];
await assert.rejects(()=>db.query(`select public.resume_training($1,'2027-01-10','ease','{"returnWeek":true}','{}',$2::jsonb)`,[conflictPause,JSON.stringify(completedUpdate)]),/completed/);
assert.equal((await db.query('select status from public.training_pauses where id=$1',[conflictPause])).rows[0].status,'paused');
assert.equal((await db.query('select plan from public.plans where id=$1',[plan])).rows[0].plan.returnWeek,true);
await db.exec(`select set_config('request.jwt.claim.sub','${other}',false);`);
assert.equal((await db.query('select count(*)::int as n from public.training_pauses')).rows[0].n,0);
await assert.rejects(()=>db.query(`select public.set_session_completion($1,'done',false)`,[session]),/Session not found/);
await assert.rejects(()=>db.query(`insert into public.training_pauses(user_id,plan_id,started_date,reason) values($1,$2,'2027-01-04','life')`,[other,plan]),/row-level security/);
await assert.rejects(()=>db.query(`insert into public.completed_sessions(user_id,session_id,date,session_title,status) values($1,$2,'2027-01-07','Long Run','done')`,[other,session]),/does not belong/);
await assert.rejects(()=>db.query(`select public.move_training_session($1,'2027-01-06')`,[session]),/Session not found/);
await db.exec(`select set_config('request.jwt.claim.sub','${user}',false);`);
await db.query(`update public.plans set plan='{"params":{"athleteContext":{"context":{"sportAvailability":{"run":["Wednesday","Thursday"]}}}}}' where id=$1`,[plan]);
const legacyId = (await db.query(`insert into public.completed_sessions(user_id,date,session_title,status,completed_at) values($1,'2027-01-07','Easy Run','done','2027-01-06T18:00:00Z') returning id`,[user])).rows[0].id;
// Existing linked identity takes precedence; every legacy row is retained.
await db.query(`select public.move_training_session($1,'2027-01-06')`,[second]);
assert.equal((await db.query('select date from public.sessions where id=$1',[second])).rows[0].date.toISOString().slice(0,10),'2027-01-06');
assert.equal((await db.query('select count(*)::int as n from public.completed_sessions where id=$1',[legacyId])).rows[0].n,1);
await assert.rejects(()=>db.query(`select public.move_training_session($1,'2027-01-08')`,[second]),/availability/);
await db.query(`select public.set_session_completion($1,'done',false)`,[second]);
assert.equal((await db.query('select count(*)::int as n from public.completed_sessions where session_id=$1',[second])).rows[0].n,1);
await db.exec('reset role;');
const third='20000000-0000-0000-0000-000000000003';
await db.query(`insert into public.sessions(id,user_id,plan_id,date,sport,title) values($1,$2,$3,'2027-01-07','run','Legacy Run')`,[third,user,plan]);
const old = (await db.query(`insert into public.completed_sessions(user_id,date,session_title,status,completed_at) values($1,'2027-01-07','Legacy Run','done','2027-01-06T18:00:00Z') returning id`,[user])).rows[0].id;
await db.exec(`set role authenticated; select set_config('request.jwt.claim.sub','${user}',false);`);
await db.query(`select public.move_training_session($1,'2027-01-06')`,[third]);
const promoted=(await db.query('select * from public.completed_sessions where id=$1',[old])).rows[0];
assert.equal(promoted.session_id,third); assert.equal(promoted.completed_at.toISOString(),'2027-01-06T18:00:00.000Z');
await db.query(`select public.set_session_completion($1,'done',false)`,[third]);
assert.equal((await db.query('select completed_at from public.completed_sessions where id=$1',[old])).rows[0].completed_at.toISOString(),promoted.completed_at.toISOString());
await db.query(`select public.set_session_completion($1,'done',true)`,[third]);
assert.equal((await db.query('select status from public.completed_sessions where id=$1',[old])).rows[0].status,'planned');
// Exact customer alternatives: move Thursday swim to Wednesday, or complete
// another Thursday swim early while preserving its original planned date.
await db.exec('reset role;');
const swim='20000000-0000-0000-0000-000000000004', earlySwim='20000000-0000-0000-0000-000000000005';
await db.query(`update public.plans set plan='{"params":{"sportAvailability":{"swim":["Tuesday"]},"athleteContext":{"context":{"sportAvailability":{"swim":["Wednesday","Thursday"]}}}}}' where id=$1`,[plan]);
await db.query(`insert into public.sessions(id,user_id,plan_id,date,sport,title) values($1,$3,$4,'2027-01-07','swim','Swim Technique'),($2,$3,$4,'2027-01-07','swim','Swim Endurance')`,[swim,earlySwim,user,plan]);
await db.exec(`set role authenticated; select set_config('request.jwt.claim.sub','${user}',false);`);
await db.query(`select public.move_training_session($1,'2027-01-06')`,[swim]);
assert.equal((await db.query('select date from public.sessions where id=$1',[swim])).rows[0].date.toISOString().slice(0,10),'2027-01-06');
await assert.rejects(()=>db.query(`select public.move_training_session($1,'2027-01-05')`,[swim]),/availability/);
await db.query(`select public.set_session_completion($1,'done',false)`,[earlySwim]);
const early=(await db.query('select date,completed_at from public.completed_sessions where session_id=$1',[earlySwim])).rows[0];
assert.equal(early.date.toISOString().slice(0,10),'2027-01-07');
assert.equal((await db.query('select date from public.sessions where id=$1',[earlySwim])).rows[0].date.toISOString().slice(0,10),'2027-01-07');
assert.ok(early.completed_at < early.date);
await db.exec('reset role; set role anon;');
await assert.rejects(()=>db.query('select * from public.training_pauses'),/permission denied/);
console.log('PASS: migrations execute; legacy history, planned/actual dates, duplicate taps, two same-sport sessions, undo, pause/resume, atomic ease-back-in, revision/completion conflicts, cross-user ownership and anonymous denial verified.');
await db.close();
